#!/bin/bash

###################################
# Start X86_64 VM with 32bit UEFI #
###################################
qemu-system-x86_64 \
-machine type=pc,accel=kvm \
-enable-kvm \
-cpu host \
-smp cores=4 \
-bios /usr/share/ovmf/ia32/ovmf_ia32.bin \
-hda /dev/sdX \ # edit /dev/sdX #
-m 4096 \
-vga std 
